import { useMemo, useState } from 'react'
import {
  Bell, Bot, Briefcase, CandlestickChart, Gauge, LayoutDashboard, Menu, Search, Settings, ShieldAlert, Target, UserCircle2, Wifi,
} from 'lucide-react'
import { motion } from 'framer-motion'
import { ColumnDef, flexRender, getCoreRowModel, useReactTable } from '@tanstack/react-table'
import { Panel, PanelGroup, PanelResizeHandle } from 'react-resizable-panels'
import { useNavigate } from 'react-router-dom'
import { navItems, useTerminalStore } from '../store/useTerminalStore'
import { useAuthStore } from '../store/useAuthStore'
import { Badge, Card, SectionHeading } from '../components/ui'
import { LightweightChart } from '../components/LightweightChart'

type OptionRow = { callOi: string; callVol: string; callIv: string; callLtp: string; callDelta: string; callGamma: string; callTheta: string; callVega: string; strike: number; putDelta: string; putGamma: string; putTheta: string; putVega: string; putLtp: string; putIv: string; putVol: string; putOi: string; bid: string; ask: string; atm: boolean }

const navMap: Record<string, string> = {
  Dashboard: '/dashboard', 'Option Chain': '/option-chain', 'Strategy Builder': '/strategy-builder', Signals: '/signals', Positions: '/positions', Orders: '/orders', Analytics: '/analytics', Alerts: '/alerts', Backtesting: '/backtesting', Settings: '/settings',
}
const navIcon = [LayoutDashboard, CandlestickChart, Target, Bot, Briefcase, ShieldAlert, Gauge, Bell, CandlestickChart, Settings]
const stats = [['Live P&L', '+$18,420', 'success'], ['Win Rate', '68.4%', 'accent'], ['Active Positions', '23', 'neutral'], ['Account Balance', '$1.28M', 'neutral'], ['Margin Used', '41%', 'danger'], ['Risk Meter', 'Moderate', 'warning']] as const

const optionRows: OptionRow[] = Array.from({ length: 1000 }, (_, i) => {
  const strike = 24200 + i * 5
  return {
    strike, atm: strike === 24750, callOi: `${150 + i}k`, callVol: `${24 + Math.floor(i / 5)}k`, callIv: (11 + i / 140).toFixed(2), callLtp: (340 - i * 0.45).toFixed(2), callDelta: (0.55 - i * 0.001).toFixed(2), callGamma: (0.03 + i * 0.00001).toFixed(3), callTheta: (-5.3 + i * 0.003).toFixed(2), callVega: (8.4 - i * 0.002).toFixed(2), putDelta: (-0.43 + i * 0.001).toFixed(2), putGamma: (0.03 + i * 0.00001).toFixed(3), putTheta: (-5.5 + i * 0.003).toFixed(2), putVega: (8.1 - i * 0.002).toFixed(2), putLtp: (10 + i * 0.45).toFixed(2), putIv: (10.5 + i / 140).toFixed(2), putVol: `${18 + Math.floor(i / 5)}k`, putOi: `${112 + i}k`, bid: (120 + i * 0.22).toFixed(2), ask: (121 + i * 0.22).toFixed(2),
  }
})

const cols: ColumnDef<OptionRow>[] = ['callOi','callVol','callIv','callLtp','callDelta','callGamma','callTheta','callVega','strike','putDelta','putGamma','putTheta','putVega','putLtp','putIv','putVol','putOi','bid','ask'].map((k)=>({accessorKey:k, header:k==='strike'?'STRIKE':k.replace(/([A-Z])/g,' $1').toUpperCase(), size:k==='strike'?96:72 }))

function DashboardView() {
  return <PanelGroup direction="vertical" autoSaveId="ws-dashboard" className="h-[calc(100vh-180px)]"><Panel defaultSize={40}><div className="grid grid-cols-2 gap-4 xl:grid-cols-6">{stats.map(([l,v,t]) => <motion.div whileHover={{ y: -2 }} key={l} className="rounded-xl border border-terminal-border-subtle bg-terminal-bg-elevated p-3"><p className="text-label-xs uppercase text-terminal-text-secondary">{l}</p><p className={`mt-2 text-value-xl font-bold ${t==='success'?'text-terminal-success':t==='accent'?'text-terminal-accent-primary':t==='danger'?'text-terminal-danger':t==='warning'?'text-terminal-warning':'text-terminal-text-primary'}`}>{v}</p></motion.div>)}</div></Panel><PanelResizeHandle className="my-2 h-1 rounded bg-terminal-border-subtle"/><Panel defaultSize={60}><div className="grid h-full gap-4 xl:grid-cols-3"><Card className="p-4 xl:col-span-2"><SectionHeading title="Market Overview" /><LightweightChart tone="#14B8A6"/></Card><Card className="p-4"><SectionHeading title="Recent Activity" /><div className="space-y-2 text-secondary-sm text-terminal-text-secondary"><p>09:31 - NIFTY Iron Condor executed</p><p>10:02 - Stop-loss updated for BANKNIFTY</p><p>10:45 - Volatility alert triggered</p><p>11:28 - Margin utilization reduced</p></div></Card></div></Panel></PanelGroup>
}

function OptionChainView() {const table=useReactTable({data:optionRows,columns:cols,getCoreRowModel:getCoreRowModel(),columnResizeMode:'onChange'});const rows=useMemo(()=>table.getRowModel().rows.slice(120,340),[table]);const [selected,setSelected]=useState<string | null>(null);return <PanelGroup direction="horizontal" autoSaveId="ws-option" className="h-[calc(100vh-180px)]"><Panel defaultSize={74}><Card className="h-full overflow-hidden"><div className="border-b border-terminal-border-subtle px-4 py-3"><div className="flex items-center gap-2 text-secondary-sm"><Badge>Index: NIFTY</Badge><Badge>Expiry: 27 JUN</Badge><Badge>Spot: 24,752</Badge><Badge>IV Rank: 42</Badge><Badge>PCR: 0.96</Badge></div></div><div className="h-[calc(100%-58px)] overflow-auto"><table className="w-[1480px] table-fixed text-[12px]"><thead className="sticky top-0 z-30 bg-terminal-bg-elevated"><tr>{table.getFlatHeaders().map((h)=><th key={h.id} style={{width:h.getSize()}} className={`group relative border-b border-terminal-border-subtle py-2 text-left text-label-xs uppercase text-terminal-text-secondary ${h.id.includes('callOi')?'pl-3':''} ${h.id.includes('strike')?'sticky left-[576px] z-40 bg-terminal-bg-elevated text-terminal-text-primary':''}`}>{flexRender(h.column.columnDef.header,h.getContext())}<div onMouseDown={h.getResizeHandler()} className="absolute right-0 top-0 h-full w-1 cursor-col-resize hover:bg-terminal-border-strong"/></th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} tabIndex={0} onClick={()=>setSelected(r.id)} className={`${i%2?'bg-terminal-bg-elevated/20':''} ${selected===r.id?'bg-terminal-bg-elevated/70':''} ${r.original.atm?'sticky top-[34px] z-20 bg-terminal-accent-primary/12':''} border-b border-terminal-border-subtle/60 hover:bg-terminal-hover/40`}>{r.getVisibleCells().map((c)=><td key={c.id} className={`py-[7px] ${c.column.id.includes('callOi')?'pl-3':''} ${c.column.id.includes('strike')?'sticky left-[576px] z-30 bg-inherit font-semibold':''}`}>{flexRender(c.column.columnDef.cell,c.getContext())}</td>)}</tr>)}</tbody></table></div></Card></Panel><PanelResizeHandle className="mx-2 w-1 rounded bg-terminal-border-subtle"/><Panel defaultSize={26}><div className="grid h-full gap-3"><Card className="p-3"><SectionHeading title="Greeks Summary"/><div className="grid grid-cols-2 gap-2 text-secondary-sm"><p>Delta: <b>+128</b></p><p>Gamma: <b>+11.2</b></p><p>Theta: <b>-82</b></p><p>Vega: <b>+44</b></p></div></Card><Card className="p-3"><SectionHeading title="OI Buildup"/><LightweightChart tone="#22C55E"/></Card><Card className="p-3"><SectionHeading title="Quick Order"/><div className="space-y-2 text-secondary-sm"><p>Symbol: NIFTY 24750 CE</p><p>Qty: 75</p><button className="rounded-xl bg-terminal-accent-primary px-3 py-2 text-label-xs font-semibold">Place Order</button></div></Card></div></Panel></PanelGroup> }

function StrategyBuilderView(){return <div className="grid h-[calc(100vh-180px)] gap-4 xl:grid-cols-3"><Card className="p-4 xl:col-span-2"><SectionHeading title="Multi-Leg Execution" /><div className="mb-3 flex flex-wrap gap-2">{['Iron Condor','Straddle','Strangle','Butterfly','Calendar Spread'].map((p)=><button key={p} className="rounded-xl border border-terminal-border-subtle px-3 py-2 text-label-xs uppercase text-terminal-text-secondary hover:bg-terminal-hover/40">{p}</button>)}</div><table className="w-full text-[12px]"><thead className="text-terminal-text-secondary"><tr><th className="text-left py-2">Strike</th><th className="text-left">Expiry</th><th className="text-left">Premium</th><th className="text-left">Delta</th><th className="text-left">Qty</th><th className="text-left">Order</th></tr></thead><tbody><tr className="border-t border-terminal-border-subtle"><td className="py-2">24700 CE</td><td>27 JUN</td><td>122.4</td><td>0.34</td><td>75</td><td>LMT</td></tr><tr className="border-t border-terminal-border-subtle"><td className="py-2">24900 CE</td><td>27 JUN</td><td>61.8</td><td>0.21</td><td>75</td><td>LMT</td></tr></tbody></table></Card><Card className="p-4"><SectionHeading title="Payoff"/><LightweightChart tone="#F59E0B"/><div className="mt-3 text-secondary-sm"><p>Break-even: 24632 / 24888</p><p>Max Profit: <b className="text-terminal-success">$2,740</b></p><p>Max Loss: <b className="text-terminal-danger">$1,260</b></p></div></Card></div>}

function GenericTable({ title, rows }: { title: string; rows: string[][] }) { return <Card className="p-4"><SectionHeading title={title}/><table className="w-full text-[12px]"><tbody>{rows.map((r,i)=><tr key={i} className="border-t border-terminal-border-subtle"><td className="py-2">{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td></tr>)}</tbody></table></Card> }

export function TerminalPage({ section = 'Dashboard' }: { section?: string }) {
  const navigate = useNavigate()
  const { activeNav, sidebarCollapsed, setActiveNav, toggleSidebar } = useTerminalStore()
  const logout = useAuthStore((s) => s.logout)

  const page = (() => {
    if (section === 'Dashboard') return <DashboardView />
    if (section === 'Option Chain') return <OptionChainView />
    if (section === 'Strategy Builder') return <StrategyBuilderView />
    if (section === 'Signals') return <GenericTable title="Signals Workspace" rows={[['NIFTY Breakout','Bullish','24,780 / 24,910','11:22'],['BANKNIFTY Reversal','Bearish','52,620 / 52,380','11:26']]} />
    if (section === 'Positions') return <GenericTable title="Positions" rows={[['NIFTY 24700 CE','75','+$2,020','Δ +23'],['BANKNIFTY 52600 PE','30','+$260','Δ -11']]} />
    if (section === 'Orders') return <GenericTable title="Order Management" rows={[['NIFTY 24700 CE','BUY 75','Completed','11:02'],['BANKNIFTY 52600 PE','SELL 30','Open','11:14']]} />
    if (section === 'Analytics') return <div className="grid gap-4 xl:grid-cols-2"><Card className="p-4"><SectionHeading title="Equity Curve"/><LightweightChart tone="#14B8A6"/></Card><Card className="p-4"><SectionHeading title="Drawdown"/><LightweightChart tone="#EF4444"/></Card></div>
    if (section === 'Alerts') return <GenericTable title="Alerts" rows={[['Price Alert','NIFTY > 24,800','Active','11:00'],['IV Alert','IV > 18','Triggered','10:42']]} />
    if (section === 'Backtesting') return <div className="grid gap-4 xl:grid-cols-2"><Card className="p-4"><SectionHeading title="Backtest Configuration"/><p className="text-secondary-sm text-terminal-text-secondary">Strategy: Iron Condor · Period: 2 Years · Capital: $100,000</p></Card><Card className="p-4"><SectionHeading title="Performance Summary"/><p className="text-secondary-sm text-terminal-text-secondary">CAGR 18.2% · Max DD 9.4% · Win Rate 64%</p></Card></div>
    return <GenericTable title="Settings" rows={[['Profile','Quant Desk Admin','Connected','Edit'],['Appearance','Dark Terminal','Active','Change'],['Risk Controls','Max Loss: 2.5%','Enabled','Configure']]} />
  })()

  return <div className="min-h-screen w-full overflow-x-hidden bg-terminal-bg-primary font-[Inter] text-terminal-text-primary antialiased"><div className="flex w-full overflow-x-hidden"><aside className={`sticky top-0 m-4 mr-0 flex h-[calc(100vh-32px)] flex-col rounded-2xl border border-terminal-border-subtle bg-terminal-bg-secondary p-4 shadow-panel transition-all duration-300 ${sidebarCollapsed ? 'w-20' : 'w-64'}`}><div className="mb-8 flex items-center justify-between"><div className="flex items-center gap-2"><CandlestickChart className="text-terminal-accent-primary" size={18} /><span className={`${sidebarCollapsed ? 'hidden' : ''} text-sm font-semibold tracking-wide`}>QuantEdge</span></div><button className="rounded-xl p-2 text-terminal-text-secondary transition-colors hover:bg-terminal-hover/40" onClick={toggleSidebar}><Menu size={16} /></button></div><nav className="space-y-2">{navItems.map((item, idx) => { const Icon = navIcon[idx]; const active = activeNav === item; return <button key={item} onClick={() => { setActiveNav(item); navigate(navMap[item] ?? '/dashboard') }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition-all ${active ? 'bg-terminal-bg-elevated text-terminal-text-primary ring-1 ring-terminal-border-strong' : 'text-terminal-text-secondary hover:bg-terminal-hover/30 hover:text-terminal-text-primary'}`}><Icon size={16} />{!sidebarCollapsed && item}</button> })}</nav></aside><main className="min-w-0 flex-1 p-4"><Card className="sticky top-4 z-20 mb-4 bg-terminal-bg-secondary px-4 py-3"><div className="flex items-center justify-between"><div className="flex min-w-[320px] items-center gap-3 rounded-xl border border-terminal-border-subtle bg-terminal-bg-elevated px-4 py-2"><Search size={16} className="text-terminal-text-secondary" /><span className="text-secondary-sm text-terminal-text-secondary">Search instruments, strategies, orders...</span></div><div className="flex items-center gap-3"><Badge tone="success">Market Open</Badge><span className="text-secondary-sm text-terminal-text-secondary">14:28:39 UTC</span><Badge tone="accent"><Wifi size={12} className="inline" /> Connected</Badge><Bell size={16} className="text-terminal-text-secondary" /><UserCircle2 size={18} className="text-terminal-text-secondary" /><button onClick={() => { logout(); navigate('/login', { replace: true }) }} className="rounded-xl bg-terminal-bg-elevated px-3 py-1 text-label-xs uppercase tracking-[0.08em] text-terminal-text-secondary hover:bg-terminal-hover/40">Logout</button></div></div></Card><h1 className="mb-4 text-page-title font-bold">{section}</h1><div className="pb-4">{page}</div></main></div></div>
}
